### ISSUE TITLE
undefined reference to stdout when using stdlib functions

### ISSUE THREAD

**Issue by oscarmattsson** [is1200-example-projects/pic32-toolchain#6]
Adding -lc to the Makefile (`LDFLAGS += -T $(LINKSCRIPT) -lc`) and including stdlib.h seems to work fine, but as soon as I add a call to any of the functions in stdlib I get the following error:

```
/opt/mcb32tools/lib/libc.a(inline.o): I funktionen "puts":
(.text+0x158): undefined reference to `stdout'
/opt/mcb32tools/lib/libc.a(inline.o): I funktionen "puts":
(.text+0x164): undefined reference to `stdout'
collect2: fel: ld returnerade avslutningsstatus 1
make: *** [outfile.elf] Fel 1
```

**Comment by h4xxel** [comment]
Declare as a global variable anywhere in your code:
void *stdout = (void *) 0;

**Comment by h4xxel** [comment]
The reasoning behind this: stdin/stdout could actually be used if you wrote functions for reading/writing from/to a serial port or other device, see https://github.com/is1200-example-projects/mcb32libc/blob/master/test/main.c

If you however do not intend to use stdout, just declare it as a pointer to NULL
